name: Prepare AKS Helm deploy
description: Deploy application service to AKS cluster
inputs:
  KubeloginVersion:
    description: Kubelogin version
    required: true
    default: "v0.0.13"

runs:
  using: "composite"
  steps:
    - name: "Login with SPN"
      uses: azure/login@v1
      with:
        client-id: ${{ env.CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        subscription-id: ${{ env.SUBSCRIPTION_ID }} 

    - name: "Install kube-login tool"
      shell: bash
      run: |
          curl -LO "https://github.com/Azure/kubelogin/releases/download/${{ inputs.KubeloginVersion }}/kubelogin-linux-amd64.zip"
          sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
          rm -f "kubelogin-linux-amd64.zip"
          kubelogin --version

    - name: "Set K8s context"
      uses: Azure/aks-set-context@v2
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP_NAME }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        subscription: ${{ env.SUBSCRIPTION_ID }}
        admin: "false"
        use-kubelogin: "true"
