name: AKS Helm deploy
description: Deploy application service to AKS cluster
inputs:      
  ClientId:
    description: Service principal client Id
    required: true        
  ClusterName:
    description: AKS cluster name
    required: true
  ClusterResourceGroupName:
    description: AKS cluster resource group name
    required: true
  KubeloginVersion:
    description: Kubelogin version
    required: true
    default: "v0.0.13"
  SubscriptionId:
    description: Service principal subscription Id
    required: true
  TenantId:
    description: Service principal tenant Id
    required: true

runs:
  using: "composite"
  steps:
    - name: "Login with SPN"
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.ClientId }}
        tenant-id: ${{ inputs.TenantId }}
        subscription-id: ${{ inputs.SubscriptionId }} 

    - name: "Install kube-login tool"
      shell: bash
      run: |
          curl -LO "https://github.com/Azure/kubelogin/releases/download/${{ inputs.KubeloginVersion }}/kubelogin-linux-amd64.zip"
          sudo unzip -j "kubelogin-linux-amd64.zip" -d /usr/local/bin
          rm -f "kubelogin-linux-amd64.zip"
          kubelogin --version

    - name: "Set K8s context"
      uses: Azure/aks-set-context@v2
      with:
        resource-group: ${{ inputs.ClusterResourceGroupName }}
        cluster-name: ${{ inputs.ClusterName }}
        subscription: ${{ inputs.SubscriptionId }}
        admin: "false"
        use-kubelogin: "true"
